import I18nProviderComponent from './I18nProvider'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <I18nProviderComponent>{children}</I18nProviderComponent>
      </body>
    </html>
  )
}
